language: objective-c
osx_image: xcode9.2
xcode_project: NetworkingKit.xcodeproj
xcode_scheme: NetworkingKit
xcode_sdk: macosx10.13

script:
  - xcodebuild clean build test -project "NetworkingKit.xcodeproj" -scheme "NetworkingKit" -destination 'generic/platform=macOS'

after_success:
  - bash <(curl -s https://codecov.io/bash)
  